matthewp/haunted

package.json
src/core.js
test/helpers.js
test/test-attrs.js
test/test.html

This adds support for observed attributes, so that setting attributes on
components will result in rerenders. Closes #6

Support observedAttributes

---

src/core.js
src/hook.js
src/symbols.js
src/use-effect.js
src/use-memo.js
src/use-reducer.js
src/use-state.js
test/helpers.js
test/test-effects.js
test/test.html

This allows memoization for useEffect:
```js
const [val, setVal] = useState(0);
useEffect(() => {
document.title = `clicked ${val} times`;
}, [val]);
```
Closes #12

Implementation memoization for useEffect

---

readme.md
src/use-effect.js
test/test-effects.js

This adds support for the teardown function in useEffect. The API
mirrors that of https://reactjs.org/docs/hooks-reference.html#cleaning-up-an-effect

Support teardown in useEffect

---

src/core.js
src/use-effect.js
test/test-effects.js

When the element is removed from the page (unmounted) tear down all
effects.

Teardown effects when element is removed

---

src/core.js
test/helpers.js
test/test-attrs.js

This adds support for boolean attributes so that when something like:
```js
<drop-down open>
```
Is used it reflects as `true` and not an empty string. Closes #21

Adds support for boolean attributes

---

test/helpers.js
test/test-attrs.js
test/test-effects.js
test/test-export.js
test/test-npm.js

Instead of using an arbitrary time to wait, instead use a full rendering
cycle (3 animation frames) when we want to wait for a render to have
occured. In the future we can make this more granular like "wait for the
render step to complete" or "wait for the commit step to complete".
Might even be able to tie it directly into the scheduler, but for now
this is an improvement.

Speed up the tests

---

readme.md

In "Getting Started" section, changed "clone" to "cloned" to be more grammatically-correct.
In "Builds" section, rewrote sentence "Haunted comes in a few builds, pick the one depending on which environment you are using:" to "Haunted comes in a few builds. Pick one based on your chosen environment:". The information is more clearly presented with a period instead of a comma, and the second sentence is more concise.
In "Cleaning up side-effects" section, changed "if" to "of" in "An example if when you..." It's more understandable now.
Fixes #29

Edits for readme.md

---

readme.md
src/component.js
src/core.js
src/haunted.js
src/lit.js
src/use-reducer.js
src/use-state.js
src/virtual.js
test/helpers.js
test/test-virtual.js
test/test.html

This adds virtual components, components that are backed by lit-html
directives.
Here's how you can use them:
```js
import { component, withHooks, useState } from '@matthewp/haunted';
import { render, html } from 'lit-html';
const Child = withHooks((foo) => {
return html`
<span>Foo: ${foo}</span>
`;
});
const App = component(() => {
return html`
<main>
${Child('bar')}
</main>
`;
});
customElements.define('my-app', App);
```
In the above example, `App` is a custom element with the name __my-app__
while `Child` is a virtual component. You can call virtual components
like normal functions and pass them arguments. They can return a
TemplateResult (the output from lit-html). They can have event handlers
and everything that regular components can have.
If they are rerendered, for example when …

Adds virtual components

---

src/haunted.js
src/use-callback.js

The React Hooks API has a `useCallback` hook that is a convenience wrapper over `useMemo`: https://reactjs.org/docs/hooks-reference.html#usecallback.

Add useCallback hook

---

Makefile

This fixes the web.js build so that it correctly finds lit-html assuming
both are sitting inside of node_modules. Closes #62

Fix web.js build

---

.travis.yml
lit-html
package.json
src/virtual.js
test/debug/virtual-teardown.html
test/test-shadow.js
test/test-virtual.js
testee.json

Directives do not have a lifecycle API. So to know when they are
removed, and call the appropriate useEffect teardown functions we now
use MutationObserver.
We do a little dance that goes like this:
* MutationObserver for when the directive node is removed from its
parent DocumentFragment (internal to lit-html).
* MutationObserver for when the directive is inserted into shadow DOM
(or whatever else I suppose).
* MutationObserver for when removed.
The last is when teardown is called. Fixes #69

Use MutationObserver to teardown virtual components

---

index.d.ts

When using `haunted` in a TS project I noticed that the `.d.ts` does not seem to have a typing for the dependencies array. At first I assumed `haunted` just didn't support one, but it seems like form looking at other issues / the code that it does? It definitely works without it so I have set it as optional in the types.

Fix useEffect typing

---

.travis.yml
package.json

This exposes haunted as a module in package.json allowing tools like [`@pika/web`](https://github.com/pikapkg/web) work with haunted.

npm module

---

index.d.ts
src/component.js
test/test-shadow.js

Fixes: #89 
See https://developers.google.com/web/fundamentals/web-components/shadowdom#focus

Add support for the delegatesFocus option when attaching the Shadow DOM

---

index.d.ts

1. Fix [issue](https://github.com/matthewp/haunted/issues/93) with missing export for the `Context interface` that prevented creating `.d.ts` files for published projects.
2. Added generics type for the `createContext()` util to allow `useContext()` to infer the context type correctly:
```ts
import {createContext, useContext} from 'haunted'
export const dataStoreContext = createContext<DataStore>({...})
const dataStore = useContext(dataStoreContext) // $ExpectType DataStore
```
3. I also thought about changing the `Context.Provider` and `Context.Consumer` from simple `Function` types, but I'm not sure what would that actually mean, because these functions constructors are inserted into the `customElements.define` and I'm not sure how or what would make the auto-complete or validation of …

Typescript context type

---

readme.md
src/use-state.js
test/test-effects.js
test/test-shadow.js
test/test-use-state.js
test/test.html

This adds the ability to provide a function as the argument to useState.
Doing so the function is only called the first time useState is run.
This is meant for expensive operations that you do not want called
multiple times (a little like useMemo).
Closes #82

Implement lazy useState

---

lib/haunted.d.ts
package.json

Hi !
This PR modifies type definitions only.
It fixes a typo in the _package.json_ "typings" field, which prevents Typescript compiler from finding the definition file.
It also changes the `shadowRootInit` option to use the "native" `ShadowRootInit` type, making the type more precise (`mode` is either `"open"` or `"closed"` instead of any string).

Typings place

---

Makefile
src/component.ts
test/test-attrs.js

This was a bug related to the `title` global attribute.

Allow the "title" attribute to be reflected

---

src/use-memo.ts

Default `values` to an empty array in `hasChanged` to prevent a cryptic error from being thrown. This is more in line with the way React handles `useMemo`/`useCallback`.
This fixes #152

Fail gracefully from `useMemo`

---

examples/lit/lit-haunted-element.js
readme.md

Improved docs of how to use LitHauntedElement. The effects of LitHauntedElement docs/example were not being cleaned up.

fix: added teardown effects in LitHaunted docs/example

---

src/use-reducer.ts
test/types-test.ts

added this third argument to useReducer so it can be used in the same manner as the example here: https://reactjs.org/docs/hooks-reference.html#usereducer

add initializer argument to useReducer

---

readme.md

Fixes #150
Fixes #151
Changelog:
- Fixed grammar
- Touched up wording everywhere
- Made the list of imports for import example longer
- Reformatted components to use the `function` syntax as discussed in #151
- Added an explanation as to why this syntax should be used
- Removed the irrelevant parts of examples (boilerplate, obvious imports)
- Elaborated in some examples to give a more detailed understanding of what's going on
- Added a section on using properties as they were only mentioned once before and in a confusing manner.
- Added a section on dispatching events as discussed in #150
- Added a small subsection explaining why virtual components don't have access to `this` and why fat arrow syntax is encouraged when writing virtual components
- Added a section explaining dependencies …

Touch up and standardize README examples

---

src/create-effect.ts
src/scheduler.ts
test/test-effects.js

Fixes #212 
In the first commit I've added a failing test for the issue and I've left in the commit with the debug logs, if you want to test it out yourself.
Here is what the log looks like:
This is the mechanism of the error:
> 1. setState is called first in #P, which queues an update (sets _updateQueued to true and queues the UPDATE phase)
> 2. setState is then called in #C, which queues an update (sets _updateQueued to true and queues the UPDATE phase)
> 3. #P scheduler handles the UPDATE phase - runs #P's render function, queues the COMMIT phase, then sets _updateQueued to false
> 4. #C scheduler handles the UPDATE phase - runs #C's render function, queues the COMMIT phase, then sets _updateQueued to false. At this point the effect hook is called the first time. (lastValues = …

Fix skipped effects

---

src/create-context.ts
src/use-context.ts

Fixes Typescript compilation error due to unsubscribe property not existing on ContextDetail when a context consumer is used without a provider.
This Typescript error is referenced in #201 and #209.

Clarify that ContextDetail.unsubscribe property may not exist

---

src/component.ts
src/create-context.ts
src/use-context.ts
test/test-props.js

Add a check to `reflectiveProp` that gives it similar behavior to `useState` and `attributeChangedCallback`: an update is only scheduled if the prop's value has changed.
Fixes [#192](https://github.com/matthewp/haunted/issues/192)

Only schedule update if prop value has changed

---

.changeset/witty-zoos-peel.md
src/create-effect.ts
test/use-effects.test.ts

Update lastValues before running the callback.
Fixes #468

fix: infinite loop if effect schedules an update and then throws

---

.changeset/polite-crabs-admire.md
src/create-context.ts
test/context.test.ts

The Context's Consumer component does not need to have a ShadowRoot because it would be very hard to style elements inside it. (part)
fixes #384

feat(create-context): don't use Shadow Root.

---

.changeset/khaki-actors-work.md
.changeset/major-coats-march.md
.changeset/quiet-mammals-look.md
.changeset/red-regions-shout.md
.changeset/salty-teams-nail.md
src/component.ts
src/core.ts
src/use-ref.ts
src/use-state.ts
src/virtual.ts

QoL improvements to types:
- **Allow omitting initialValue from useRef**
- **export Ref type**
- **Export type `Options` from component as `ComponentOptions`.**
- **Improvements to useState**
Fixes #466

QoL improvements to types
