.gitignore, Makefile, index.js, package.json, readme.md, test/test-npm.js
This adds the build for bundler users and documents the three options.
=> Add the bundler build

readme.md
This adds a section on Getting Started. Maybe in the future I'll add
some more stuff here but for now it just links to the codesandbox I
created.
=> Link to the codesandbox

test/test-props.js, test/test.html
The first time a component renders.
=> Adds a test to verify that properties are passed

src/use-effect.js, test/test-effects.js
=> Ensure useEffect with an empty array runs only once

readme.md, src/core.js, test/test-attrs.js, test/test-export.js
fixes typo in readme
binds this context on non-arrow function components
ref: https://github.com/matthewp/haunted/issues/26
=> binds this context to components defined as non-arrow functions

readme.md
This project works for hyperHTML (6 months out before lit-html) so it'd be cool to not make it a lit-html thing only.
Thanks.
=> Mention hyperHTML too

Makefile, src/core.js
This adds support for 0.13. Breaking change :(
=> Support lit-html 0.13

examples/theme.html, package-lock.json, readme.md, src/core.js, src/create-context.js, src/haunted.js, src/symbols.js, src/use-context.js, src/virtual.js, test/test-context.js, test/test.html
=> WIP feature/context

readme.md
Not sure if you want the link to my repo. I plan to leave it there as reference. If you'd prefer to copy it into an examples folder, feel free to help yourself.
=> IE11 Example

Makefile, package.json, src/lit.js
This will be a breaking change.
=> Upgrade to lit-html 0.14

src/use-state.js
Addresses #43 
Calls updater function when a function is passed to a `useState` setter:
```js
// counter.js
import { virtual, useMemo } from "haunted";
import { html } from "lit-html";
export default virtual(({ value, setValue }) => {
const increment = useMemo(() => () => setValue(val => val + 1), []);
return html`
<button @click=${increment}>${value}</button>
`;
});
```
```js
// index.js
import { component, useState } from "haunted";
import { html } from "lit-html";
import Counter from "./counter";
const App = component(() => {
const [count, setCount] = useState(0);
return html`
<h1>Count for me!</h1>
${Counter({ value: count, setValue: setCount })}
`;
});
customElements.define("x-app", App);
```
=> Add useState updater function

package.json
=> Run the build as a previous task

Makefile, package.json, readme.md, src/lit.js, yarn.lock
This upgrades us to the release candidate. Closes #49
=> Upgrade to lit-html 1.0 release candidate

src/component.js, test/test-attrs.js
addresses https://github.com/matthewp/haunted/issues/55
=> Convert dash attributes to camelCase props

package.json, readme.md
Not 100% sure if removing the blurb in the readme about haunted@next is the right move, but figured I'm open this for discussion at least...
=> bump lit-html and update readme

package.json
In previous PR I missed adding the new types file to the npm files array...
=> add index.d.ts to npm files array so it gets included in package

readme.md
This needs to be still wrapped by component. See https://github.com/matthewp/haunted/blob/fe66090bf0efa625ec4c52d25189ea1f18c3cc1c/test/test-attrs.js
=> Add missing component call in the observedAttributes example

.travis.yml, package.json, testee.json, yarn.lock
This fixes CI tests so that headless chrome is used. Closes #117
=> Make CI tests use headless chrome

lib/component.js, lib/haunted.d.ts, readme.md, test/test-attrs.js
=> Allow to pass observedAttributes as an option and make BaseElement argument optional in component()

.travis.yml, lib/component.js, lib/haunted.d.ts, package.json, readme.md, test/test-attrs.js, test/types-test.ts, testee.json, yarn.lock
Enhanced types definition.
#115 
#88
=> Enhanced Typescript types definitions

lib/component.js, test/test-export.js
=> Ensure Components are instances of HTMLElement

readme.md, src/core.ts, src/create-effect.ts, src/scheduler.ts, src/state.ts, src/symbols.ts, src/use-effect.ts, src/use-layout-effect.ts, test/test-layout-effects.js, test/test-virtual.js, test/test.html
Hi !
Here my implementation of the useLayoutEffect, mentioned in #120 and #133.
This PR includes the changes of #133, so I'll wait until the first one is merged to mark it ready for review.
=> Add useLayoutEffect hook

src/component.ts
Fixes #186 #166 
Replaces PR #190
=> Fix native properties

examples/controllers/mouse-controller.js, examples/use-controller.html, package-lock.json, package.json, readme.md, src/core.ts, src/use-controller.ts, src/use-state.ts, test/test-use-controller.js
* use useController to compose ReactiveControllers into haunted components
* tests useController
* documents useController in examples
Closes #237
=> feat: add useController hook

package.json
=> Move @lit/reactive-element to a real dep

package-lock.json, package.json, src/component.ts
This fixes compat with some parent classes which set properties in the
constructor. We just set them now and don't try to schedule an update
(when the scheduler hasn't been created yet)
=> Prevent running updates during construction

rocket.config.js
fallback to default playground-ide behaviour (load from unpkg)
=> docs: revert import map to 4.8.1

.changeset/khaki-elephants-fold.md, package-lock.json, package.json, src/use-controller.ts, src/use-state.ts, test/use-state.test.ts
=> useState: Prevent updating when the value hasn't changed 

.changeset/forty-times-sink.md, .github/workflows/ci.yml, package-lock.json, package.json, src/hook.ts, web-test-runner.config.mjs
Keep the workflows up to date.
Update dependencies and allow Lit v3.
=> Update workflows and dependencies

.github/workflows/ci.yml
Adjust workflows.
Instead of using the build artefact re-build before release.
=> Adjust workflows
